ballresponse = [
                   'Yes',
                   'No',
                   'Take a wild guess...',
                   'Very doubtful',
                   'Sure',
                   'Without a doubt',
                   'Most likely',
                   'Might be possible',
                   "You'll be the judge",
                   'no... (╯°□°）╯︵ ┻━┻',
                   'no... baka',
                   'you need to chill out'
                   'senpai, pls no ;-;',
                   'no you noob',
                   'Better not tell you now'
               ],
badwords = [
    'fuck',
    'fck',
    'ass',
    'anus',
    'arse',
    'ballsack',
    'bastard',
    'bitch',
    'biatch',
    'bloody',
    'blowjob',
    'blow job',
    # 'bollock',
    # 'bollok',
    # 'boner',
    # 'boob',
    # 'bugger',
    # 'butt',
    # 'buttplug',
    # 'clitoris',
    # 'cock',
    # 'coon',
    # 'cunt',
    # 'dick',
    # 'dyke',
    # 'fag',
    # 'feck',
    # 'fellate',
    # 'fellatio',
    # 'felching',
    # 'fuck',
    # 'f u c k',
    # 'fudgepacker',
    # 'fudge packer',
    # 'flange',
    # 'Goddamn',
    # 'God damn',
    # 'nigger',
    # 'nigga',
    # 'pussy',
    # 'vagina',
    # 'wank',
]
